### ISSUE TITLE
[BUG] Missing EthersError type with Typescript

### ISSUE THREAD

**Issue by challet** [enzoferey/ethers-error-parser#39]
**Describe the bug**

Using the `getParsedEthersError` in a typescript file leads to this error

```ts
TS2345: Argument of type 'unknown' is not assignable to parameter of type 'EthersError'.
    37 |       contract = yield call(async() => await factory.deploy(payload))
    38 |     } catch(e) {
  > 39 |       getParsedEthersError(e)
       |                            ^
    40 |     }
```

And trying to import it is not working : 
> Module '"@enzoferey/ethers-error-parser"' has no exported member 'EthersError'.

**Expected behavior**

The library exposes the types that may be used externally, so this can be written : 
```ts
import { getParsedEthersError, EthersError } from "@enzoferey/ethers-error-parser"
[…]
getParsedEthersError(e as EthersError)
```

**Comment by challet** [comment]
I made a PR which resolves my issue locally. But did I missed something ? I'm wondering since the README example is already written in Typescript and doesn't need to import that `EthersError` type.

**Comment by enzoferey** [comment]
Hi @challet ! Thanks for bringing up this issue.

You are completely right, the example of the README is not using TypeScript just in case somebody does not use it, but you are right in TypeScript will need to cast the `error` value from the `catch` statement to some compatible type.

Internally, we always cast like `error as Error` as the signatures overlap and you generally want to asses if it is really an Ethers error in the first place or not. But it is definitely not the best approach.

Let's follow up on your PR to see what's the best way to tackle it 👍🏻
