### ISSUE TITLE
Minor error in typescript example

### ISSUE THREAD

**Issue by zed-wong** [enzoferey/ethers-error-parser#46]
Missing 'type' for `EthersError`
from
```
import {
  getParsedEthersError,
  EthersError,
} from "@enzoferey/ethers-error-parser";
```
to
```
import {
  getParsedEthersError,
  type EthersError,
} from "@enzoferey/ethers-error-parser";
```

**Comment by enzoferey** [comment]
Hey @zed-wong, do you mean on the README examples ? I believe using `import type` is on the user's side to decide depending on this setup and tooling. Using such imports is optional, and does not provide much value as of today.

What are your thoughts ?

**Comment by zed-wong** [comment]
Idk sir, I just copied that into my VSCode and the compiler says that's the correct way of importing types. Sorry if I was wrong.

**Comment by enzoferey** [comment]
Oh yes, sure, as I say it depends on your project's configuration. Do whatever works for you best, but the syntax is valid for sure 😁 

Closing the issue, thanks for bringing the topic up 👍🏻
