### ISSUE TITLE
[FEATURE] Handle Nonce Errors

### ISSUE THREAD

**Issue by JohnSmithyy** [enzoferey/ethers-error-parser#9]
Would it be possible to handle/parse nonce errors?

As an example:

`Error: nonce has already been used [ See: https://links.ethers.org/v5-errors-NONCE_EXPIRED ] (error={"code":-32603,"message":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32000,\"message\":\"Nonce too low. Expected nonce to be 117 but got 1.\",\"data\":{\"message\":\"Nonce too low. Expected nonce to be 117 but got 1.\"}}}}'","stack":"{\n  \"code\": -32603,\n  \"message\": \"[ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32603,\\\"data\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"Nonce too low. Expected nonce to be 117 but got 1.\\\",\\\"data\\\":{\\\"message\\\":\\\"Nonce too low. Expected nonce to be 117 but got 1.\\\"}}}}'\",\n  \"stack\": \"Error: [ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32603,\\\"data\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"Nonce too low. Expected nonce to be 117 but got 1.\\\",\\\"data\\\":{\\\"message\\\":\\\"Nonce too low. Expected nonce to be 117 but got 1.\\\"}}}}'\\n `

**Comment by enzoferey** [comment]
Hey @JohnSmithyy ! Thanks for submitting this issue, it is definitely a type of error we want to handle.

I will have a look at it and work on supporting it 👍🏻

**Comment by enzoferey** [comment]
@JohnSmithyy This feature is now supported on version `0.2.0` => https://www.npmjs.com/package/@enzoferey/ethers-error-parser/v/0.2.0
